# Generated by Django 5.2.4 on 2025-07-08 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='nouveau', max_length=50)),
                ('priority', models.CharField(default='basse', max_length=50)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de plainte',
                'verbose_name_plural': 'Tickets de plainte',
                'ordering': ['-submission_date'],
            },
        ),
    ]
