# Generated by Django 5.2.4 on 2025-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en cours de traitement', 'En cours de traitement'), ('resolu', 'Résolu'), ('ignore', 'Ignoré')], default='nouveau', max_length=50),
        ),
    ]
