# Generated by Django 5.2.4 on 2025-07-10 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email du plaignant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom du plaignant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom du plaignant'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='message',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='platform_name',
            field=models.CharField(max_length=100, verbose_name="Plateforme d'origine"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('critique', 'Critique')], default='basse', max_length=50, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en cours de traitement', 'En cours de traitement'), ('resolu', 'Résolu'), ('ignore', 'Ignoré')], default='nouveau', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Sujet du ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de soumission'),
        ),
    ]
